version: "3"
services:
  ##############
  # API Service
  ##############
  api-ws:
    build:  
      context: ../api/bin/api-ws
    container_name: '${COMPOSE_PROJECT_NAME}-api-ws'
    restart: always
    volumes:
      - ${DOCUMENT_ROOT-./src}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${APACHE_LOG_DIR-../ws/appdata/api/api-ws/log/apache2}:/var/log/apache2
      - ${SYMFONY_VAR_DIR-../ws/appdata/api/api-ws/data/symfony}:/var/www/html/var
    environment:
      VIRTUAL_HOST: edgebox,edgebox.local,api.edgebox.local${INTERNET_URL}
