name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Install dependencies
        run: |
          cd src/
          composer install
      - name: Setup app
        run: |
          cd src/
          ./bin/console doctrine:schema:create
      - name: Run tests
        run: |
          cd src/
          XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover coverage.xml
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: src/coverage.xml
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Install dependencies
        run: |
          cd src/
          composer install
      - name: Run PHPStan
        run: |
          cd src/
          ./vendor/bin/phpstan analyse
