name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Install dependencies
        run: |
          cd src/
          composer install
      - name: Setup app
        run: |
          ./bin/console doctrine:schema:create
          ./bin/console doctrine:migrations:migrate -n
      - name: Run tests
        run: |
          cd src/
          ./bin/phpunit
