name: CI
on: [push]
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Install dependencies
        run: |
          cd src/
          composer install
      - name: Run tests
        run: |
          cd src/
          ./bin/phpunit
